// <auto-generated />
using System;
using HalkEgitimSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HalkEgitimSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416123748_AddInstructorAuth")]
    partial class AddInstructorAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HalkEgitimSistemi.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TcNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplyDate = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CertificateCode = "HE-2026-0001",
                            CourseId = 1,
                            Email = "ali.koc@email.com",
                            FirstName = "Ali",
                            IsCompleted = true,
                            LastName = "Koç",
                            PhoneNumber = "0532 111 22 33",
                            Status = 1,
                            TcNo = "12345678901"
                        },
                        new
                        {
                            Id = 2,
                            ApplyDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CertificateCode = "HE-2026-0002",
                            CourseId = 4,
                            Email = "ayse.demir@email.com",
                            FirstName = "Ayşe",
                            IsCompleted = true,
                            LastName = "Demir",
                            PhoneNumber = "0533 222 33 44",
                            Status = 1,
                            TcNo = "23456789012"
                        },
                        new
                        {
                            Id = 8,
                            ApplyDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 14,
                            Email = "derya.ozturk@email.com",
                            FirstName = "Derya",
                            IsCompleted = false,
                            LastName = "Öztürk",
                            PhoneNumber = "0539 888 99 00",
                            Status = 1,
                            TcNo = "89012345678"
                        },
                        new
                        {
                            Id = 3,
                            ApplyDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 8,
                            Email = "mehmet.yilmaz@email.com",
                            FirstName = "Mehmet",
                            IsCompleted = false,
                            LastName = "Yılmaz",
                            PhoneNumber = "0534 333 44 55",
                            Status = 0,
                            TcNo = "34567890123"
                        },
                        new
                        {
                            Id = 4,
                            ApplyDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 11,
                            Email = "fatma.kara@email.com",
                            FirstName = "Fatma",
                            IsCompleted = false,
                            LastName = "Kara",
                            PhoneNumber = "0535 444 55 66",
                            Status = 0,
                            TcNo = "45678901234"
                        },
                        new
                        {
                            Id = 5,
                            AdminNote = "Kontenjan doldu.",
                            ApplyDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Email = "hasan.celik@email.com",
                            FirstName = "Hasan",
                            IsCompleted = false,
                            LastName = "Çelik",
                            PhoneNumber = "0536 555 66 77",
                            Status = 2,
                            TcNo = "56789012345"
                        },
                        new
                        {
                            Id = 6,
                            ApplyDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 10,
                            Email = "zeynep.aydin@email.com",
                            FirstName = "Zeynep",
                            IsCompleted = false,
                            LastName = "Aydın",
                            PhoneNumber = "0537 666 77 88",
                            Status = 1,
                            TcNo = "67890123456"
                        },
                        new
                        {
                            Id = 7,
                            ApplyDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 13,
                            Email = "emre.sahin@email.com",
                            FirstName = "Emre",
                            IsCompleted = false,
                            LastName = "Şahin",
                            PhoneNumber = "0538 777 88 99",
                            Status = 0,
                            TcNo = "78901234567"
                        });
                });

            modelBuilder.Entity("HalkEgitimSistemi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Bilişim Teknolojileri",
                            Description = "Yazılım, donanım ve dijital beceriler",
                            IconClass = "bi-laptop"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Yabancı Diller",
                            Description = "İngilizce, Almanca, Arapça dil kursları",
                            IconClass = "bi-translate"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "El Sanatları",
                            Description = "Ahşap boyama, nakış, seramik atölyeleri",
                            IconClass = "bi-palette"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Müzik",
                            Description = "Enstrüman ve ses eğitimi programları",
                            IconClass = "bi-music-note-beamed"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Spor ve Sağlık",
                            Description = "Fitness, yoga, yüzme kursları",
                            IconClass = "bi-heart-pulse"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Aşçılık ve Pastacılık",
                            Description = "Mutfak sanatları ve gastronomi",
                            IconClass = "bi-cup-hot"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Güzellik ve Bakım",
                            Description = "Kuaförlük, cilt bakımı, makyaj",
                            IconClass = "bi-scissors"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Mesleki Eğitim",
                            Description = "Sertifikalı mesleki gelişim programları",
                            IconClass = "bi-briefcase"
                        });
                });

            modelBuilder.Entity("HalkEgitimSistemi.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CourseName = "Python Programlama",
                            Description = "Sıfırdan ileri seviyeye Python programlama. Veri analizi, web geliştirme ve otomasyon projeleri.",
                            DurationHours = 80,
                            EndDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=600",
                            IsActive = true,
                            Quota = 25,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CourseName = "Web Tasarım (HTML/CSS)",
                            Description = "Modern web sitesi tasarımı. HTML5, CSS3, Bootstrap ve responsive tasarım teknikleri.",
                            DurationHours = 60,
                            EndDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1547658719-da2b51169166?w=600",
                            IsActive = true,
                            Quota = 30,
                            StartDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CourseName = "Bilgisayar İşletmenliği",
                            Description = "Ofis programları, dosya yönetimi ve temel bilgisayar becerileri sertifika programı.",
                            DurationHours = 120,
                            EndDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600",
                            IsActive = true,
                            Quota = 35,
                            StartDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CourseName = "İngilizce A1-A2",
                            Description = "Başlangıç seviyesi İngilizce. Temel dilbilgisi, kelime hazinesi ve günlük konuşma pratiği.",
                            DurationHours = 90,
                            EndDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1543109740-4bdb38fda756?w=600",
                            IsActive = true,
                            Quota = 20,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CourseName = "Almanca Temel Kurs",
                            Description = "Almanca dilbilgisi, telaffuz ve kültürel iletişim becerileri.",
                            DurationHours = 60,
                            EndDate = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1527866959252-deab85ef7d1b?w=600",
                            IsActive = true,
                            Quota = 15,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CourseName = "Ahşap Boyama Atölyesi",
                            Description = "Dekoratif ahşap boyama teknikleri, renk uyumu ve uygulama becerileri.",
                            DurationHours = 40,
                            EndDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600",
                            IsActive = true,
                            Quota = 20,
                            StartDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CourseName = "Seramik ve Çömlek",
                            Description = "El yapımı seramik ve çömlek üretimi. Şekillendirme, sırlama ve fırınlama teknikleri.",
                            DurationHours = 50,
                            EndDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600",
                            IsActive = true,
                            Quota = 15,
                            StartDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CourseName = "Gitar Kursu",
                            Description = "Klasik ve akustik gitar eğitimi. Nota okuma, akor geçişleri ve parça çalışmaları.",
                            DurationHours = 45,
                            EndDate = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600",
                            IsActive = true,
                            Quota = 12,
                            StartDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CourseName = "Bağlama (Saz) Kursu",
                            Description = "Türk Halk Müziği enstrümanı bağlama/saz eğitimi. Temel ve orta seviye.",
                            DurationHours = 50,
                            EndDate = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=600",
                            IsActive = true,
                            Quota = 15,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CourseName = "Yoga ve Pilates",
                            Description = "Beden ve zihin sağlığı için yoga ve pilates programı. Tüm seviyelere uygundur.",
                            DurationHours = 36,
                            EndDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600",
                            IsActive = true,
                            Quota = 25,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CourseName = "Türk Mutfağı",
                            Description = "Geleneksel Türk yemekleri, kebaplar, çorbalar ve tatlılar. Uygulamalı mutfak eğitimi.",
                            DurationHours = 60,
                            EndDate = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600",
                            IsActive = true,
                            Quota = 18,
                            StartDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CourseName = "Pastacılık ve Hamur İşleri",
                            Description = "Profesyonel pastacılık teknikleri, pasta süsleme, ekmek ve börek yapımı.",
                            DurationHours = 50,
                            EndDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1486427944544-d2c246c4df14?w=600",
                            IsActive = true,
                            Quota = 15,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            CourseName = "Kuaförlük ve Saç Bakımı",
                            Description = "Profesyonel saç kesimi, boyama, fön ve bakım teknikleri. MEB sertifikalı.",
                            DurationHours = 120,
                            EndDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600",
                            IsActive = true,
                            Quota = 20,
                            StartDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 8,
                            CourseName = "Muhasebe ve Finans",
                            Description = "Temel muhasebe, bilanço okuma, vergi mevzuatı ve finansal analiz.",
                            DurationHours = 90,
                            EndDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600",
                            IsActive = true,
                            Quota = 30,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            CourseName = "Girişimcilik Atölyesi",
                            Description = "İş planı oluşturma, pazarlama stratejileri, dijital girişimcilik ve hibe programları.",
                            DurationHours = 40,
                            EndDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600",
                            IsActive = true,
                            Quota = 25,
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HalkEgitimSistemi.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            FullName = "Dr. Ahmet Yılmaz",
                            Title = "Bilişim Teknolojileri Öğretmeni"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            FullName = "Elif Kaya",
                            Title = "Web Tasarım Uzmanı"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            FullName = "Mehmet Demir",
                            Title = "Bilgisayar Eğitmeni"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            FullName = "Sarah Johnson",
                            Title = "İngilizce Öğretmeni"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            FullName = "Hans Weber",
                            Title = "Almanca Öğretmeni"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            FullName = "Zeynep Arslan",
                            Title = "El Sanatları Ustası"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 7,
                            FullName = "Fatma Çelik",
                            Title = "Seramik Sanatçısı"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 8,
                            FullName = "Can Özkan",
                            Title = "Müzik Öğretmeni"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 9,
                            FullName = "Hasan Korkmaz",
                            Title = "Halk Müziği Sanatçısı"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 10,
                            FullName = "Ayşe Yıldırım",
                            Title = "Yoga Eğitmeni"
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 11,
                            FullName = "Şef Mustafa Bey",
                            Title = "Aşçıbaşı"
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 12,
                            FullName = "Pınar Aydın",
                            Title = "Pastacılık Ustası"
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 13,
                            FullName = "Derya Şahin",
                            Title = "Kuaför / Güzellik Uzmanı"
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 14,
                            FullName = "Burak Öztürk",
                            Title = "Mali Müşavir"
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 15,
                            FullName = "Prof. Dr. Selin Aktaş",
                            Title = "Girişimcilik Danışmanı"
                        });
                });

            modelBuilder.Entity("HalkEgitimSistemi.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Halk Eğitim Merkezimizin 2026 yaz dönemi kurs kayıtları başlamıştır. 15 farklı branşta ücretsiz eğitim fırsatı! Kontenjanlar sınırlıdır, acele edin.",
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "https://images.unsplash.com/photo-1523050854058-8df90110c476?w=600",
                            PublishDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "2026 Yaz Dönemi Kayıtları Başladı!"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bilişim teknolojileri kategorisinde yeni Python Programlama kursu açılmıştır. Yapay zeka ve veri bilimi alanına adım atmak isteyenler için harika bir fırsat.",
                            Date = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=600",
                            PublishDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Python Programlama Kursu Açıldı"
                        },
                        new
                        {
                            Id = 3,
                            Content = "2025-2026 eğitim dönemini başarıyla tamamlayan 450 kursiyerimize sertifikaları düzenlenen törenle verildi. Tüm mezunlarımızı tebrik ederiz.",
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=600",
                            PublishDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sertifika Töreni Gerçekleştirildi"
                        },
                        new
                        {
                            Id = 4,
                            Content = "KOSGEB işbirliğiyle düzenlenen ücretsiz girişimcilik semineri 15 Haziran'da merkezimizde gerçekleştirilecektir. Tüm vatandaşlarımız davetlidir.",
                            Date = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600",
                            PublishDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ücretsiz Girişimcilik Semineri"
                        });
                });

            modelBuilder.Entity("HalkEgitimSistemi.Models.Application", b =>
                {
                    b.HasOne("HalkEgitimSistemi.Models.Course", "Course")
                        .WithMany("Applications")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HalkEgitimSistemi.Models.Course", b =>
                {
                    b.HasOne("HalkEgitimSistemi.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HalkEgitimSistemi.Models.Instructor", b =>
                {
                    b.HasOne("HalkEgitimSistemi.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HalkEgitimSistemi.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("HalkEgitimSistemi.Models.Course", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
